title: jQuery.filterSelect
description: jQuery.filterSelect is a jQuery based plugin that populate multiples select elements through AJAX requests, chaining one selected element to fill another/others.
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
